name: Build & Push Docs Image

on:
  push:
    tags:
      - "v*.*"  # trigger on version tags
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history needed for mike

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mike

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy docs with mike
        env:
          DOCS_VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy --push --update-aliases $DOCS_VERSION latest
          mike set-default --push latest
          mkdir docs-site
          git fetch origin gh-pages
          git --work-tree=docs-site checkout origin/gh-pages -- .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docs-site
          file: compose/production/docs/Dockerfile
          push: true
          tags: |
            eubucco/eubucco-docs:${{ github.ref_name }}
            eubucco/eubucco-docs:latest
